version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: xlarge

    steps:
      - run:
          name: Setup packages
          command: |
            sudo apt update && sudo apt install neofetch -y && neofetch && df -h
